CREATE TABLE users (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	login VARCHAR(30) NOT NULL,
	password VARCHAR(30) NOT NULL,
	name VARCHAR(50) NOT NULL,
	passed INT UNSIGNED NOT NULL,
	tests INT UNSIGNED NOT NULL
	);
CREATE TABLE sessions (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	uid INT NOT NULL,
	ip VARCHAR(50) NOT NULL,
	sid VARCHAR(128) NOT NULL
	);
CREATE TABLE groups (
	groupid VARCHAR(50) PRIMARY KEY,
	name VARCHAR(50) NOT NULL
	);
INSERT INTO groups (groupid, name) VALUES ("edu", "Образовательное");
INSERT INTO groups (groupid, name) VALUES ("fun", "Развлечения");
CREATE TABLE tests (
	testid INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	content BLOB NOT NULL,
	answers BLOB NOT NULL,
	groupid VARCHAR(50) NOT NULL,
	uid INT NOT NULL
	);