CREATE TABLE users (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	login VARCHAR(30) NOT NULL,
	password VARCHAR(30) NOT NULL,
	name VARCHAR(50) NOT NULL,
	passed INT UNSIGNED NOT NULL,
	tests INT UNSIGNED NOT NULL
	);
CREATE TABLE sessions (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	uid INT NOT NULL,
	ip VARCHAR(50) NOT NULL,
	sid VARCHAR(128) NOT NULL
	);